spring:
  application:
    name: "orion-rest-service"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost/orion-rest-service"
    username: postgres
    password: cbhma8hq
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true

logging:
  file:
    name: spring.log
  level:
    org:
      hibernate:
        type: info
server:
  port: 8080